log_dir: /pscratch/sd/a/ayz2/PLASIM_logs
#log_dir: logs
project_name: PLASIM_flow_matching
devices: 4
accelerator: gpu
strategy: ddp
seed: 42
description: large_perl

model:
    name: dit
    num_fa_blocks: 12
    num_sa_blocks: 12
    num_ca_blocks: 6
    patch_size: 2
    cond_dim: 1536
    num_cond: 2 # day of year, hour of day
    num_constants: 6 # lsm sg z0; rsdt sic sst
    dim: 1536
    num_heads: 32
    in_dim: 146  # 5 multilevel vars * 13 levels = 65 + 8 surface features = 73 * 2 (past timestep + noise) = 146
    out_dim: 73 # only predict noise 
    proj_bottleneck_dim: 1536
    kernel_expansion_ratio: 1.0
    depth_dropout: 0.0
    scale_by_sigma: True
    l_max: 20

data:
    # perlmutter paths
    train_data_path: /pscratch/sd/a/ayz2/PLASIM/processed_new/PLASIM_train_146096.h5
    val_data_path: /pscratch/sd/a/ayz2/PLASIM/processed_new/PLASIM_valid_1460.h5
    train_times_path: /pscratch/sd/a/ayz2/PLASIM/processed_new/PLASIM_train_146096_times.pkl
    val_times_path: /pscratch/sd/a/ayz2/PLASIM/processed_new/PLASIM_valid_1460_times.pkl
    norm_stats_path: /pscratch/sd/a/ayz2/PLASIM/processed_new/norm_stats.npz
    boundary_path: /pscratch/sd/a/ayz2/PLASIM/processed/boundary_vars.h5

    # local paths
    #train_data_path: /data/PLASIM/PLASIM_train_10000.h5
    #val_data_path: /data/PLASIM/PLASIM_valid_1460.h5
    #train_times_path: /data/PLASIM/PLASIM_train_10000_times.pkl
    #val_times_path: /data/PLASIM/PLASIM_valid_1460_times.pkl
    #norm_stats_path: /data/PLASIM/PLASIM/norm_stats.npz
    #boundary_path: /data/PLASIM/PLASIM/boundary_vars.h5

    training_nsteps: 1 # train on next-step prediction
    val_nsteps: 40 # valid up to 40 steps
    nlat: 64
    nlon: 128
    with_poles: False
    load_into_memory: False

training:
    lr: 1.7e-4
    min_lr: 1.e-7
    beta1: 0.9
    beta2: 0.95
    
    check_val_every_n_epoch: 1
    log_every_n_steps: 100
    max_epochs: 10
    checkpoint: null

    batch_size_per_device: 8
    eval_batch_size: 16
    num_workers: 16
    gradient_accumulation_steps: 1
    skip_step: 0
    gradient_clip_val: 1.0

    num_refinement_steps: 5 # 5
    num_train_steps: 11
    min_noise_std: 1.e-3 # useless for flow
    noise_schedule: flow
    noise_type: sphere
    spherical_l_max: 32 # useless for gaussian
    noise_input: False
    input_noise_scale: 1.e-1

    integrator: euler
    restart: False
    restart_step: 8

    visualize: True